<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>ei8.Cortex.Coding.d23</AssemblyName>
    <RootNamespace>ei8.Cortex.Coding.d23</RootNamespace>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>$(DefineConstants);</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Grannies\**" />
    <Compile Remove="neurULization\**" />
    <EmbeddedResource Remove="Grannies\**" />
    <EmbeddedResource Remove="neurULization\**" />
    <None Remove="Grannies\**" />
    <None Remove="neurULization\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ei8.Cortex.Coding" Version="0.3.5" />
    <PackageReference Include="ei8.Cortex.Coding.Spiker" Version="0.1.7" />
  </ItemGroup>
	
</Project>
